fix vim syntastic: --parse-only => -Z parse-only
when saving .rs files under vim
do not fail to run the syntax checker
error: Unrecognized option: 'parse-only'.

due to this commit
fe4fdc56a35d060daf6b17cdf94b17642dfc68e1
which removed the deprecated flag --parse-only